### PR TITLE
Just in case others modify and have CR/LFs in their api/secret files

### PR DESCRIPTION
**Pull request by PaulSandoz**
To reduce potential auth errors.

### CODE REVIEW

**Comment by PaulSandoz** [comment]
Actually it might be better to push to the trim into lein-cloudbees instead.

**Comment by michaelneale** [comment]
yeah I might change lein-cloudbees to do this.

Also - is there a better way to read/manage keys ? look in ~/.bees/bees.config and read it as a properties file?

**Comment by PaulSandoz** [comment]
Yes. If the cloudbees-api-key and cloudbees-api-secret are not explicitly declared we should slurp 'em from that properties file, if present. Unless you get to it before me I can take a stab at that this week and submit a pull request.

**Comment by michaelneale** [comment]
OK I will put any changes in lein-cloudbees and re-release when happy with it.

**Comment by PaulSandoz** [comment]
I was not clear, plan to push something to lein-cloudbees, less work for you :-)

**Pull request closed without merging**
